// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Providers } from "./providers";
import { ToastContainer } from 'react-toastify';

const generalSans = localFont({
  src: "../components/assets/fonts/fonts/GeneralSans-Regular.woff",
  variable: "--font-general-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Amus",
  description: "Generated by Colin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} antialiased`}>
        <Providers>{children}</Providers>
        <ToastContainer />
      </body>
    </html>
  );
}
