import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const generalSans = localFont({
  src: "../components/assets/fonts/fonts/GeneralSans-Regular.woff",
  variable: "--font-general-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Amus",
  description: "Generated by Colin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
      <body className={`${generalSans.variable}  antialiased`}>{children}</body>
    </html>
 
  );
}
