// app/layout.tsx
import type { Metadata } from "next";
import "./chatbot.css";
import "./globals.css";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import Assistant from "./assistant";

const generalSans = localFont({
  src: "../components/assets/fonts/fonts/GeneralSans-Regular.woff",
  variable: "--font-general-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Amus",
  description: "Generated by Colin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.variable} antialiased`}>
        <Assistant />

        <ToastContainer />
      </body>
    </html>
  );
}
